### ISSUE TITLE
[Done] WorkUnit 981-986

### ISSUE THREAD

**Issue by funkyface** [hube12/SSG#10]
- [x] 981 [finalOutput_981.txt](https://github.com/hube12/SSG/files/5016324/finalOutput_981.txt)
- [x] 982 [finalOutput_982.txt](https://github.com/hube12/SSG/files/5017279/finalOutput_982.txt)
- [x] 983 [finalOutput_983.txt](https://github.com/hube12/SSG/files/5021284/finalOutput_983.txt)
- [x] 984 [finalOutput_984.txt](https://github.com/hube12/SSG/files/5021285/finalOutput_984.txt)
- [x] 985 [finalOutput_985.txt](https://github.com/hube12/SSG/files/5021288/finalOutput_985.txt)
- [x] 986 [finalOutput_986.txt](https://github.com/hube12/SSG/files/5021289/finalOutput_986.txt)

**Comment by funkyface** [comment]
[finalOutput_981.txt](https://github.com/hube12/SSG/files/5016324/finalOutput_981.txt)

**Comment by funkyface** [comment]
All done

**Comment by hube12** [comment]
thx
