### ISSUE TITLE
Doing workunits 963-967

### ISSUE THREAD

**Issue by bleach86** [hube12/SSG#14]

**Comment by bleach86** [comment]
[finalOutput_963.txt](https://github.com/hube12/SSG/files/5019852/finalOutput_963.txt)
[finalOutput_964.txt](https://github.com/hube12/SSG/files/5019854/finalOutput_964.txt)
[finalOutput_965.txt](https://github.com/hube12/SSG/files/5019855/finalOutput_965.txt)
[finalOutput_966.txt](https://github.com/hube12/SSG/files/5019857/finalOutput_966.txt)
[finalOutput_967.txt](https://github.com/hube12/SSG/files/5019858/finalOutput_967.txt)

**Comment by hube12** [comment]
assimilated
