### ISSUE TITLE
[Done] WorkUnits 300-305

### ISSUE THREAD

**Issue by AlpacaFur** [hube12/SSG#17]
- [x] 300 [finalOutput_300.txt](https://github.com/hube12/SSG/files/5018164/finalOutput_300.txt)
- [x] 301 [finalOutput_301.txt](https://github.com/hube12/SSG/files/5018728/finalOutput_301.txt)
- [x] 302 [finalOutput_302.txt](https://github.com/hube12/SSG/files/5019534/finalOutput_302.txt)
- [x] 303 [finalOutput_303.txt](https://github.com/hube12/SSG/files/5019535/finalOutput_303.txt)
- [x] 304 [finalOutput_304.txt](https://github.com/hube12/SSG/files/5019536/finalOutput_304.txt)
- [x] 305 [finalOutput_305.txt](https://github.com/hube12/SSG/files/5019538/finalOutput_305.txt)

**Comment by hube12** [comment]
Hi, this is ok but please consider that in the future we only go from 1024 down, since gcp has 0 to 255 and 512 to 768 reserved

**Comment by AlpacaFur** [comment]
Ah, sorry about that, I just noticed that it was an empty space. If it's more convenient for you, I can switch now, as I've only just started 300.

**Comment by hube12** [comment]
no its ok i reserved the spot for ya
