### ISSUE TITLE
[Done] WorkUnits 306-310

### ISSUE THREAD

**Issue by Frederic94500** [hube12/SSG#18]
- [x] 306 [finalOutput_306.txt](https://github.com/hube12/SSG/files/5019092/finalOutput_306.txt)
- [x] 307 [finalOutput_307.txt](https://github.com/hube12/SSG/files/5019381/finalOutput_307.txt)
- [x] 308 [finalOutput_308.txt](https://github.com/hube12/SSG/files/5021604/finalOutput_308.txt)
- [x] 309 [finalOutput_309.txt](https://github.com/hube12/SSG/files/5021586/finalOutput_309.txt)
- [x] 310 [finalOutput_310.txt](https://github.com/hube12/SSG/files/5021590/finalOutput_310.txt)

**Comment by hube12** [comment]
assimilated thx!
