### ISSUE TITLE
Doing WorkUnits 900-909

### ISSUE THREAD

**Issue by AlpacaFur** [hube12/SSG#19]
- [x] 900 [finalOutput_900.txt](https://github.com/hube12/SSG/files/5019710/finalOutput_900.txt)
- [x] 901 [finalOutput_901.txt](https://github.com/hube12/SSG/files/5022221/finalOutput_901.txt)
- [x] 902 [finalOutput_902.txt](https://github.com/hube12/SSG/files/5022223/finalOutput_902.txt)
- [x] 903 [finalOutput_903.txt](https://github.com/hube12/SSG/files/5022600/finalOutput_903.txt)
- [x] 904 [finalOutput_904.txt](https://github.com/hube12/SSG/files/5023483/finalOutput_904.txt)
- [x] 905 [finalOutput_905.txt](https://github.com/hube12/SSG/files/5023484/finalOutput_905.txt)
- [x] 906 [finalOutput_906.txt](https://github.com/hube12/SSG/files/5023485/finalOutput_906.txt)
- [ ] 907
- [ ] 908
- [ ] 909

**Comment by hube12** [comment]
missing 907 908 909 (indication for me)

**Comment by hube12** [comment]
done
