### ISSUE TITLE
WorkUnits 768-799

### ISSUE THREAD

**Issue by FxMorin** [hube12/SSG#20]
- [x] 768 [finalOutput_768.txt](https://github.com/hube12/SSG/files/5019906/finalOutput_768.txt)
- [x] 769 [finalOutput_769.txt](https://github.com/hube12/SSG/files/5019908/finalOutput_769.txt)
- [x] 770 [finalOutput_770.txt](https://github.com/hube12/SSG/files/5019927/finalOutput_770.txt)
- [x] 771 [finalOutput_771.txt](https://github.com/hube12/SSG/files/5020117/finalOutput_771.txt)
- [x] 772 [finalOutput_772.txt](https://github.com/hube12/SSG/files/5022524/finalOutput_772.txt)
- [x] 773 [finalOutput_773.txt](https://github.com/hube12/SSG/files/5022527/finalOutput_773.txt)
- [x] 774 [finalOutput_774.txt](https://github.com/hube12/SSG/files/5022531/finalOutput_774.txt)
- [x] 775 [finalOutput_775.txt](https://github.com/hube12/SSG/files/5022534/finalOutput_775.txt)
- [x] 776 [finalOutput_776.txt](https://github.com/hube12/SSG/files/5022538/finalOutput_776.txt)
- [x] 777 [finalOutput_777.txt](https://github.com/hube12/SSG/files/5022541/finalOutput_777.txt)
- [x] 778 [finalOutput_778.txt](https://github.com/hube12/SSG/files/5022549/finalOutput_778.txt)
- [x] 779 [finalOutput_779.txt](https://github.com/hube12/SSG/files/5022551/finalOutput_779.txt)
- [x] 780 [finalOutput_780.txt](https://github.com/hube12/SSG/files/5022773/finalOutput_780.txt)
- [x] 781 [finalOutput_781.txt](https://github.com/hube12/SSG/files/5024418/finalOutput_781.txt)
- [x] 782 [finalOutput_782.txt](https://github.com/hube12/SSG/files/5028809/finalOutput_782.txt)
- [x] 783 [finalOutput_783.txt](https://github.com/hube12/SSG/files/5028812/finalOutput_783.txt)
- [x] 784 [finalOutput_784.txt](https://github.com/hube12/SSG/files/5028813/finalOutput_784.txt)
- [x] 785 [finalOutput_785.txt](https://github.com/hube12/SSG/files/5028814/finalOutput_785.txt)
- [x] 786 [finalOutput_786.txt](https://github.com/hube12/SSG/files/5028815/finalOutput_786.txt)
- [x] 787 [finalOutput_787.txt](https://github.com/hube12/SSG/files/5028816/finalOutput_787.txt)
- [ ] 788
- [ ] 789
- [ ] 790
- [ ] 791
- [ ] 792
- [ ] 793
- [ ] 794
- [ ] 795
- [ ] 796
- [ ] 797
- [ ] 798
- [ ] 799

Well, this is going to be fun!
- PR0CESS

**Comment by FxMorin** [comment]
Btw, I am AnotherBot on discord xD

**Comment by hube12** [comment]
i noticed

**Comment by hube12** [comment]
from the pfp

**Comment by FxMorin** [comment]
780 was much larger, is there a reason why some take less time and some take a lot more?

**Comment by hube12** [comment]
shall i redistribute the remaining?

**Comment by hube12** [comment]
done
