### ISSUE TITLE
doing workunits 501-511

### ISSUE THREAD

**Issue by bleach86** [hube12/SSG#21]

**Comment by bleach86** [comment]
[finalOutput_501.txt](https://github.com/hube12/SSG/files/5025692/finalOutput_501.txt)
[finalOutput_502.txt](https://github.com/hube12/SSG/files/5025693/finalOutput_502.txt)
[finalOutput_503.txt](https://github.com/hube12/SSG/files/5025694/finalOutput_503.txt)
[finalOutput_504.txt](https://github.com/hube12/SSG/files/5025696/finalOutput_504.txt)
[finalOutput_505.txt](https://github.com/hube12/SSG/files/5025697/finalOutput_505.txt)
[finalOutput_506.txt](https://github.com/hube12/SSG/files/5025698/finalOutput_506.txt)
[finalOutput_507.txt](https://github.com/hube12/SSG/files/5025700/finalOutput_507.txt)
[finalOutput_508.txt](https://github.com/hube12/SSG/files/5025701/finalOutput_508.txt)
[finalOutput_509.txt](https://github.com/hube12/SSG/files/5025702/finalOutput_509.txt)
[finalOutput_510.txt](https://github.com/hube12/SSG/files/5025703/finalOutput_510.txt)
[finalOutput_511.txt](https://github.com/hube12/SSG/files/5025704/finalOutput_511.txt)

**Comment by hube12** [comment]
thx
