### ISSUE TITLE
[Done!!!] WorkUnits 317 and 319-330

### ISSUE THREAD

**Issue by Frederic94500** [hube12/SSG#22]
- [x] 317 [finalOutput_317.txt](https://github.com/hube12/SSG/files/5021869/finalOutput_317.txt)
- [x] 318 (taken by Neil)
- [x] 319 [finalOutput_319.txt](https://github.com/hube12/SSG/files/5022196/finalOutput_319.txt)
- [x] 320 [finalOutput_320.txt](https://github.com/hube12/SSG/files/5022036/finalOutput_320.txt)
- [x] 321 [finalOutput_321.txt](https://github.com/hube12/SSG/files/5023949/finalOutput_321.txt)
- [x] 322 [finalOutput_322.txt](https://github.com/hube12/SSG/files/5023950/finalOutput_322.txt)
- [x] 323 [finalOutput_323.txt](https://github.com/hube12/SSG/files/5023954/finalOutput_323.txt)
- [x] 324 [finalOutput_324.txt](https://github.com/hube12/SSG/files/5023956/finalOutput_324.txt)
- [x] 325 [finalOutput_325.txt](https://github.com/hube12/SSG/files/5023957/finalOutput_325.txt)
- [x] 326 [finalOutput_326.txt](https://github.com/hube12/SSG/files/5023959/finalOutput_326.txt)
- [x] 327 [finalOutput_327.txt](https://github.com/hube12/SSG/files/5023963/finalOutput_327.txt)
- [x] 328 [finalOutput_328.txt](https://github.com/hube12/SSG/files/5023964/finalOutput_328.txt)
- [x] 329 [finalOutput_329.txt](https://github.com/hube12/SSG/files/5024179/finalOutput_329.txt)
- [x] 330 [finalOutput_330.txt](https://github.com/hube12/SSG/files/5024181/finalOutput_330.txt)

**Comment by hube12** [comment]
miss 329 330 (indication for me)

**Comment by Frederic94500** [comment]
It's working ^^

**Comment by Frederic94500** [comment]
@hube12 Finished ^^

**Comment by hube12** [comment]
assimilated
