### ISSUE TITLE
WorkUnits 331-350

### ISSUE THREAD

**Issue by BoySanic** [hube12/SSG#23]
- [x] 331
- [x] 332
- [x] 333
- [x] 334
- [x] 335
- [x] 336
- [x] 337
- [x] 338
- [x] 339
- [x] 340
- [x] 341
- [x] 342
- [x] 343
- [x] 344
- [x] 345
- [x] 346
- [x] 347
- [x] 348
- [x] 349
- [x] 350

**Comment by BoySanic** [comment]
[finalOutput_331.txt](https://github.com/hube12/SSG/files/5022041/finalOutput_331.txt)

**Comment by BoySanic** [comment]
[finalOutput_332.txt](https://github.com/hube12/SSG/files/5022357/finalOutput_332.txt)

**Comment by BoySanic** [comment]
[finalOutput_333.txt](https://github.com/hube12/SSG/files/5022725/finalOutput_333.txt)

**Comment by BoySanic** [comment]
[finalOutput_334.txt](https://github.com/hube12/SSG/files/5023140/finalOutput_334.txt)

**Comment by hube12** [comment]
shall i redistribute the remaining?

**Comment by BoySanic** [comment]
[finalOutput_338.txt](https://github.com/hube12/SSG/files/5028234/finalOutput_338.txt)
[finalOutput_339.txt](https://github.com/hube12/SSG/files/5028235/finalOutput_339.txt)
[finalOutput_340.txt](https://github.com/hube12/SSG/files/5028236/finalOutput_340.txt)
[finalOutput_341.txt](https://github.com/hube12/SSG/files/5028237/finalOutput_341.txt)
[finalOutput_342.txt](https://github.com/hube12/SSG/files/5028238/finalOutput_342.txt)
[finalOutput_343.txt](https://github.com/hube12/SSG/files/5028239/finalOutput_343.txt)
[finalOutput_344.txt](https://github.com/hube12/SSG/files/5028240/finalOutput_344.txt)
[finalOutput_345.txt](https://github.com/hube12/SSG/files/5028241/finalOutput_345.txt)
[finalOutput_346.txt](https://github.com/hube12/SSG/files/5028242/finalOutput_346.txt)
[finalOutput_347.txt](https://github.com/hube12/SSG/files/5028243/finalOutput_347.txt)
[finalOutput_348.txt](https://github.com/hube12/SSG/files/5028244/finalOutput_348.txt)
[finalOutput_349.txt](https://github.com/hube12/SSG/files/5028245/finalOutput_349.txt)
[finalOutput_350.txt](https://github.com/hube12/SSG/files/5028246/finalOutput_350.txt)
[finalOutput_335.txt](https://github.com/hube12/SSG/files/5028247/finalOutput_335.txt)
[finalOutput_336.txt](https://github.com/hube12/SSG/files/5028248/finalOutput_336.txt)
[finalOutput_337.txt](https://github.com/hube12/SSG/files/5028249/finalOutput_337.txt)

**Comment by hube12** [comment]
thx
