### ISSUE TITLE
[Done] WorkUnit 380-383

### ISSUE THREAD

**Issue by funkyface** [hube12/SSG#24]
- [x] 380 [finalOutput_380.txt](https://github.com/hube12/SSG/files/5026461/finalOutput_380.txt)
- [x] 381 [finalOutput_381.txt](https://github.com/hube12/SSG/files/5026462/finalOutput_381.txt)
- [x] 382 [finalOutput_382.txt](https://github.com/hube12/SSG/files/5027716/finalOutput_382.txt)
- [x] 383 [finalOutput_383.txt](https://github.com/hube12/SSG/files/5027718/finalOutput_383.txt)

**Comment by hube12** [comment]
thx !
