### ISSUE TITLE
WorkUnits 920-929

### ISSUE THREAD

**Issue by Grifs99** [hube12/SSG#25]
- [x] 920 [finalOutput_920.txt](https://github.com/hube12/SSG/files/5023993/finalOutput_920.txt)
- [x] 921 [finalOutput_921.txt](https://github.com/hube12/SSG/files/5023994/finalOutput_921.txt)
- [x] 922 [finalOutput_922.txt](https://github.com/hube12/SSG/files/5025255/finalOutput_922.txt)
- [x] 923 [finalOutput_923.txt](https://github.com/hube12/SSG/files/5023996/finalOutput_923.txt)
- [x] 924 [finalOutput_924.txt](https://github.com/hube12/SSG/files/5025258/finalOutput_924.txt)
- [x] 925 [finalOutput_925.txt](https://github.com/hube12/SSG/files/5023997/finalOutput_925.txt)
- [x] 926 [finalOutput_926.txt](https://github.com/hube12/SSG/files/5023998/finalOutput_926.txt)
- [x] 927 [finalOutput_927.txt](https://github.com/hube12/SSG/files/5023999/finalOutput_927.txt)
- [x] 928 [finalOutput_928.txt](https://github.com/hube12/SSG/files/5024000/finalOutput_928.txt)
- [x] 929 [finalOutput_929.txt](https://github.com/hube12/SSG/files/5024001/finalOutput_929.txt)

**Comment by hube12** [comment]
miss 922 924 (indication for me)

**Comment by Grifs99** [comment]
Hey @hube12 

I have added the last two output files (922, 924). 👍

**Comment by hube12** [comment]
done
