### ISSUE TITLE
Doing work units 1012-1017

### ISSUE THREAD

**Issue by bleach86** [hube12/SSG#3]

**Comment by bleach86** [comment]
[finalOutput_1012.txt](https://github.com/hube12/SSG/files/5013189/finalOutput_1012.txt)

**Comment by bleach86** [comment]
[finalOutput_1013.txt](https://github.com/hube12/SSG/files/5015597/finalOutput_1013.txt)

**Comment by bleach86** [comment]
[finalOutput_1014.txt](https://github.com/hube12/SSG/files/5015598/finalOutput_1014.txt)

**Comment by bleach86** [comment]
[finalOutput_1016.txt](https://github.com/hube12/SSG/files/5016107/finalOutput_1016.txt)

**Comment by bleach86** [comment]
[finalOutput_1015.txt](https://github.com/hube12/SSG/files/5017296/finalOutput_1015.txt)

**Comment by bleach86** [comment]
[finalOutput_1017.txt](https://github.com/hube12/SSG/files/5017300/finalOutput_1017.txt)

**Comment by hube12** [comment]
uploaded
